// <auto-generated />
namespace SportsTech.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class EventParticipantsCircularDependency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventParticipantsCircularDependency));
        
        string IMigrationMetadata.Id
        {
            get { return "201401190747542_EventParticipants-CircularDependency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
